### ISSUE TITLE
HTTP error published to discord channel when ritual participant is too long

### ISSUE THREAD

**Issue by KPrasch** [nucypher/tacobot#4]
![Screenshot from 2024-01-25 11-54-37](https://github.com/nucypher/tacobot/assets/679404/ffba605d-b71b-4e30-bb96-4d4ae3d3567c)

**Comment by derekpierre** [comment]
This should be fixed via two changes:
1. For `tacobot` (for requests on information about a specific ritual) - https://github.com/nucypher/tacobot/commit/859274e02cda3a89557f87fe0acdba37861b6045
2. For `pique` (used for automated printing of events; in this case it applies to `StartRitual` for which the participants parameter is long) - https://github.com/KPrasch/pique/pull/1/commits/8ada409096d18d75e025caa88a3bc1c20b8302df.
